# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_2.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1232, 866)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(560, 50, 661, 761))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView.setGeometry(QtCore.QRect(20, 30, 621, 721))
        self.graphicsView.setAutoFillBackground(False)
        self.graphicsView.setObjectName("graphicsView")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 531, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.file_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.file_name.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        self.file_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.file_name.setObjectName("file_name")
        self.horizontalLayout.addWidget(self.file_name)
        self.label_txt = QtWidgets.QLabel(self.layoutWidget)
        self.label_txt.setObjectName("label_txt")
        self.horizontalLayout.addWidget(self.label_txt)
        self.btn_choose = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_choose.setObjectName("btn_choose")
        self.horizontalLayout.addWidget(self.btn_choose)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 490, 531, 321))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.text_con = QtWidgets.QTextEdit(self.groupBox_3)
        self.text_con.setGeometry(QtCore.QRect(10, 30, 511, 281))
        self.text_con.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.text_con.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.text_con.setReadOnly(True)
        self.text_con.setObjectName("text_con")
        self.groupBox_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_1.setGeometry(QtCore.QRect(10, 90, 531, 391))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.groupBox_1.setFont(font)
        self.groupBox_1.setTitle("")
        self.groupBox_1.setObjectName("groupBox_1")
        self.table_enter_matrix = QtWidgets.QTableWidget(self.groupBox_1)
        self.table_enter_matrix.setGeometry(QtCore.QRect(10, 30, 511, 351))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.table_enter_matrix.setFont(font)
        self.table_enter_matrix.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.table_enter_matrix.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_enter_matrix.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_enter_matrix.setWordWrap(True)
        self.table_enter_matrix.setRowCount(0)
        self.table_enter_matrix.setObjectName("table_enter_matrix")
        self.table_enter_matrix.setColumnCount(0)
        self.table_enter_matrix.horizontalHeader().setCascadingSectionResizes(False)
        self.table_enter_matrix.horizontalHeader().setDefaultSectionSize(60)
        self.table_enter_matrix.horizontalHeader().setStretchLastSection(False)
        self.label_circle_presence = QtWidgets.QLabel(self.centralwidget)
        self.label_circle_presence.setGeometry(QtCore.QRect(560, 10, 661, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_circle_presence.setFont(font)
        self.label_circle_presence.setText("")
        self.label_circle_presence.setObjectName("label_circle_presence")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 50, 531, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_count = QtWidgets.QPushButton(self.widget)
        self.btn_count.setObjectName("btn_count")
        self.horizontalLayout_2.addWidget(self.btn_count)
        self.btn_clear = QtWidgets.QPushButton(self.widget)
        self.btn_clear.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_clear.setAutoFillBackground(False)
        self.btn_clear.setCheckable(False)
        self.btn_clear.setAutoExclusive(False)
        self.btn_clear.setFlat(False)
        self.btn_clear.setObjectName("btn_clear")
        self.horizontalLayout_2.addWidget(self.btn_clear)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1232, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Пошук Ейлерового циклу"))
        self.label_txt.setText(_translate("MainWindow", ".txt"))
        self.btn_choose.setText(_translate("MainWindow", "Вибрати"))
        self.btn_count.setText(_translate("MainWindow", "Знайти"))
        self.btn_clear.setText(_translate("MainWindow", "Очистити все"))


