# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_5.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1763, 958)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_left = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_left.setGeometry(QtCore.QRect(10, 10, 591, 891))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.groupBox_left.setFont(font)
        self.groupBox_left.setTitle("")
        self.groupBox_left.setObjectName("groupBox_left")
        self.graphicsView_left = QtWidgets.QGraphicsView(self.groupBox_left)
        self.graphicsView_left.setGeometry(QtCore.QRect(10, 30, 571, 801))
        self.graphicsView_left.setAutoFillBackground(False)
        self.graphicsView_left.setObjectName("graphicsView_left")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_left)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 850, 571, 35))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_left = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_left.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_left.setObjectName("horizontalLayout_left")
        self.file_name_left = QtWidgets.QLineEdit(self.layoutWidget)
        self.file_name_left.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        self.file_name_left.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.file_name_left.setObjectName("file_name_left")
        self.horizontalLayout_left.addWidget(self.file_name_left)
        self.label_txt_left = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_txt_left.setFont(font)
        self.label_txt_left.setObjectName("label_txt_left")
        self.horizontalLayout_left.addWidget(self.label_txt_left)
        self.btn_choose_left = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.btn_choose_left.setFont(font)
        self.btn_choose_left.setObjectName("btn_choose_left")
        self.horizontalLayout_left.addWidget(self.btn_choose_left)
        self.groupBox_right = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_right.setGeometry(QtCore.QRect(1160, 10, 591, 891))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.groupBox_right.setFont(font)
        self.groupBox_right.setTitle("")
        self.groupBox_right.setObjectName("groupBox_right")
        self.graphicsView_right = QtWidgets.QGraphicsView(self.groupBox_right)
        self.graphicsView_right.setGeometry(QtCore.QRect(10, 30, 571, 811))
        self.graphicsView_right.setAutoFillBackground(False)
        self.graphicsView_right.setObjectName("graphicsView_right")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_right)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 850, 571, 35))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_right = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_right.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_right.setObjectName("horizontalLayout_right")
        self.file_name_right = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.file_name_right.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        self.file_name_right.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.file_name_right.setObjectName("file_name_right")
        self.horizontalLayout_right.addWidget(self.file_name_right)
        self.label_txt_right = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_txt_right.setFont(font)
        self.label_txt_right.setObjectName("label_txt_right")
        self.horizontalLayout_right.addWidget(self.label_txt_right)
        self.btn_choose_right = QtWidgets.QPushButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.btn_choose_right.setFont(font)
        self.btn_choose_right.setObjectName("btn_choose_right")
        self.horizontalLayout_right.addWidget(self.btn_choose_right)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(620, 10, 521, 891))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.text_con = QtWidgets.QTextEdit(self.groupBox)
        self.text_con.setGeometry(QtCore.QRect(10, 620, 501, 221))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_con.setFont(font)
        self.text_con.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.text_con.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.text_con.setReadOnly(True)
        self.text_con.setObjectName("text_con")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 850, 501, 34))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_center = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_center.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_center.setObjectName("horizontalLayout_center")
        self.btn_count = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_count.setObjectName("btn_count")
        self.horizontalLayout_center.addWidget(self.btn_count)
        self.btn_clear = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_clear.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_clear.setAutoFillBackground(False)
        self.btn_clear.setCheckable(False)
        self.btn_clear.setAutoExclusive(False)
        self.btn_clear.setFlat(False)
        self.btn_clear.setObjectName("btn_clear")
        self.horizontalLayout_center.addWidget(self.btn_clear)
        self.label_res = QtWidgets.QLabel(self.groupBox)
        self.label_res.setGeometry(QtCore.QRect(10, 590, 499, 24))
        self.label_res.setText("")
        self.label_res.setObjectName("label_res")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 20, 501, 561))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_left = QtWidgets.QLabel(self.widget)
        self.label_left.setText("")
        self.label_left.setObjectName("label_left")
        self.verticalLayout.addWidget(self.label_left)
        self.table_enter_matrix_left = QtWidgets.QTableWidget(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.table_enter_matrix_left.setFont(font)
        self.table_enter_matrix_left.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.table_enter_matrix_left.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_enter_matrix_left.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_enter_matrix_left.setWordWrap(True)
        self.table_enter_matrix_left.setRowCount(0)
        self.table_enter_matrix_left.setObjectName("table_enter_matrix_left")
        self.table_enter_matrix_left.setColumnCount(0)
        self.table_enter_matrix_left.horizontalHeader().setCascadingSectionResizes(False)
        self.table_enter_matrix_left.horizontalHeader().setDefaultSectionSize(60)
        self.table_enter_matrix_left.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.table_enter_matrix_left)
        self.label_right = QtWidgets.QLabel(self.widget)
        self.label_right.setText("")
        self.label_right.setObjectName("label_right")
        self.verticalLayout.addWidget(self.label_right)
        self.table_enter_matrix_right = QtWidgets.QTableWidget(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.table_enter_matrix_right.setFont(font)
        self.table_enter_matrix_right.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.table_enter_matrix_right.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_enter_matrix_right.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_enter_matrix_right.setWordWrap(True)
        self.table_enter_matrix_right.setRowCount(0)
        self.table_enter_matrix_right.setObjectName("table_enter_matrix_right")
        self.table_enter_matrix_right.setColumnCount(0)
        self.table_enter_matrix_right.horizontalHeader().setCascadingSectionResizes(False)
        self.table_enter_matrix_right.horizontalHeader().setDefaultSectionSize(60)
        self.table_enter_matrix_right.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.table_enter_matrix_right)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1763, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Перевірка на Ізоморфність"))
        self.label_txt_left.setText(_translate("MainWindow", ".txt"))
        self.btn_choose_left.setText(_translate("MainWindow", "Вибрати файл 1"))
        self.label_txt_right.setText(_translate("MainWindow", ".txt"))
        self.btn_choose_right.setText(_translate("MainWindow", "Вибрати файл 2"))
        self.btn_count.setText(_translate("MainWindow", "Перевірити на Ізоморфізм"))
        self.btn_clear.setText(_translate("MainWindow", "Очистити все"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
